### ISSUE TITLE
Issue with junit output from awspec verifier.

### ISSUE THREAD

**Issue by twllight** [neillturner/kitchen-verifier-awspec#1]
Hello,
I have a question regarding getting junit formatting to work however. This definitely may be due to my lack of ruby experience and if that is the case I apologize for the noob comment!

I have setup my kitchen.yml as follows:
```
-bash-4.2$ cat .kitchen.yml
driver:
  name: terraform
  backend_configurations:
    region:     "us-east-1"
    bucket:     "<<snip>>"
    key:        "<<snip>>"
    lock_table: "<<snip>>"
  variable_files:
    - "../variables/terraform.tfvars.json"

provisioner:
  name: terraform
  directory: <<snip>>
  variable_files:
    - ../variables/terraform.tfvars.json

platforms:
  - name: centos

transport:
  name: ssh
  ssh_key: <<snip>>

verifier:
  name: awspec
  format: RspecJunitFormatter
  output: ./awspec_output.xml

suites:
    - name: consul-specs
      verifier:
        default_pattern: true
```
When running tests, tests are outputted to stdout in correct junit format. However, no xml file is written at all, as i would assume would be due to the output: key.

my rspec command runs and shows the correct formater
```
12:51:02 kitchen-terraform_1  |        Running Awspec
12:51:02 kitchen-terraform_1  |        Using default pattern /tmp/terraform/backend-infrastructure/consul/spec/*_spec.rb
12:51:02 kitchen-terraform_1  |        Running command: rspec -c -f RspecJunitFormatter --default-path  /tmp/terraform/backend-infrastructure/consul  -P /tmp/terraform/backend-infrastructure/consul/spec/*_spec.rb
12:51:04 kitchen-terraform_1  | /tmp/terraform/backend-infrastructure/consul
```
If this is the wrong place i'll be happy to close. thank you for taking the time to have a look!

**Comment by neillturner** [comment]
I'm not sure if i need to write any code in the verifier-awspec to support Junit format. 
there are a few interesting link around 
 http://hedge-ops.com/cookbook-development-with-rakefile/
I would run the test kitchen command with -l debug at the end to get all the debug output which may help you figure out the config required  
i would be vary of using  ./ prefix for awspec_output.xml. 
try with a full path. the -l debug might show you what it is doing with this. 
try googling for test kitchen RspecJunitFormatter

**Comment by twllight** [comment]
Hey 
Thanks for peeking at this I actually figured it out a bit ago I’ll post the solution when I’m close to a pc so as to help anyone else. Thanks again!

**Comment by hatched-DavidMichon** [comment]
@twllight Can you post your solution here please?

**Comment by dominic-byrne-worldpay** [comment]
For anyone stumbling on to this issue, you can get junit test reports by adding the `format` and `extra_flags` keys to your test suite like this:

```
suites:
  - name: "default"
    verifier:
      name: "awspec"
      patterns:
      - "spec/*.rb"
      format: RspecJunitFormatter
      extra_flags: '--out result.xml"
```
